---
- name: Install node and npm
  hosts: 192.168.3.231
  tasks: 
    - name: update apt repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: 192.168.3.231
  vars_files:
    - project-vars
  tasks: 
    - name: Create linux user
      user:
        name: linux_name
        comment: "{{ linux_name }} user"
        group: adm

- name: Deploy nodejs app
  hosts: 192.168.3.231
  become: True
  become_user: linux_name
  vars_files:
    - project-vars
  # vars:
  #   - location: /home/linux_name
  #   - version: 1.0.0
  #   - user_home_directory: /home/linux_name
  tasks: 
    # - name: Copy nodejs folder to a server
    #   copy:
    #     src:  /Users/adwiz/Downloads/bootcamp-node-envvars-project-{{ version }}.tgz
    #     dest: "{{ user_home_directory }}/app-{{ version }}.tgz
    - name: Unpack the nodejs file
      unarchive: 
        src: "{{ location }}/app-{{ version }}.tgz"
        dest: "{{ user_home_directory }}" 
        remote_src: yes
    - name: Install dependencies
      npm: 
        path: "{{ user_home_directory }}/package"
    - name: Start the application
      command: 
        chdir: "{{ user_home_directory }}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: 
        msg: "{{ app_status.stdout_lines }}"