---
- name: Install docker
  hosts: docker_server
  become: yes
  tasks:
    - name: update apt repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install docker
      apt: 
        pkg: docker
        state: present 

